name: "Run Container Scan on Super Mario Docker Image with Quality Gate"

#on:
#  push:
#    branches:
#      - main

jobs:
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read and Increment Version
        run: |
          VERSION=$(( $(cat version.txt) + 1 ))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "$VERSION" > version.txt  # Optionally update the version file
          cat version.txt

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker Image from Docker Hub
        run: |
          docker pull docker.io/jermainejordan/supermariogitopsproject:${{ env.VERSION }}

      - name: Run Trivy vulnerability scanner on Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/jermainejordan/supermariogitopsproject:${{ env.VERSION }}
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
